name: python

on: push

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - uses: actions/checkout@v4
        
    - name: Test env vars for python
      run: |
        export ENVVAR
        python dev/ci/test_env_var_defined.py 
      env:
        ENVVAR: ${{ env.ENVVAR }} 
        SECRET: ${{ env.SECRET }} 